version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      #- cluster.initial_master_nodes=es
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/es/data
    ports:
      - 9200:9200
    networks:
      - esnet

#  elasticsearch2:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
#    container_name: elasticsearch2
#    environment:
#      - cluster.initial_master_nodes=es
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "discovery.zen.ping.unicast.hosts=es"
#      - http.cors.enabled=true
#      - http.cors.allow-origin=*
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata2:/usr/share/es/data
#    networks:
#      - esnet

  # elasticsearch3:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
  #   container_name: elasticsearch3
  #   environment:
  #     - cluster.initial_master_nodes=es
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=es"
  #     - http.cors.enabled=true
  #     - http.cors.allow-origin=*
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata3:/usr/share/es/data
  #   networks:
  #     - esnet

#  kibana:
#    image: 'docker.elastic.co/kibana/kibana:7.5.0'
#    container_name: kibana
#    environment:
#      SERVER_NAME: kibana.local
#      ELASTICSEARCH_URL: http://es:9200
#    ports:
#      - '5601:5601'
#    networks:
#      - esnet
#    depends_on:
#      - es
#      - elasticsearch2

  # headPlugin:
  #  image: 'mobz/es-head:5'
  #  container_name: head
  #  ports:
  #    - '9100:9100'
  #  networks:
  #    - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local    

networks:
  esnet: